### ISSUE TITLE
Attribute minSdkVersion did not checked

### ISSUE THREAD

**Issue by WilliamChen98** [HiFromAjay/ManifestInspector#1]
I'm using your program to check some Android Manifest files, and I found that some of them didn't set the minSdkVersion, and your program will be crashed and show these Exceptions:

Exception in thread "main" java.lang.NumberFormatException: For input string: " "
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:776)
	at com.android.manifest.AMSecurity.checkExposedProviders(AMSecurity.java:339)
	at com.android.manifest.AMSecurity.checkSecurity(AMSecurity.java:36)
	at com.android.manifest.ManifestInspector.main(ManifestInspector.java:28)

I assume that you didn't check if minSdkVersion is declared. In the official document of android shows that if minSdkVersion is not declared, it will be assumed as 1. So maybe you should check it.

int minSdk = 0;
if(elem.getAttribute("android:minSdkVersion").equals("")) {
            minSdk = 1;
}else {
            minSdk = Integer.parseInt(elem.getAttribute("android:minSdkVersion"));
}

I add these code above, and it seems to solve the problem. Maybe this will help you to improve your program.

**Comment by HiFromAjay** [comment]
You are right. I had missed the checking.
